"""Build sequence-coupled meta features from K=4 PRIMARY OOF + test predictions.

The thesis: every prior meta-feature in this project is a function of a single
row's K-base predictions, so any new base whose row-level prediction lies in
the [P, rank, logit] expansion gets absorbed (A29). Sequence-coupled features
break that hidden row-independence assumption.

OOF discipline: the K=4 PRIMARY OOF for row L was generated by a model trained
on folds≠f_L. When we use OOF[L] as a look-ahead feature for row R (in fold k),
no leakage occurs because OOF[L] doesn't encode R's target. The same OOF[L] is
used for all rows that look at L, regardless of which fold they belong to.

Features built per row R in (Driver, Race, Year), sorted by LapNumber:
- look_ahead_pred  — K=4 PRIMARY OOF at the next observed row in the session
- look_ahead_gap   — LapNumber distance to that next row (default = 99 if none)
- look_behind_pred — K=4 PRIMARY OOF at the previous observed row
- look_behind_gap  — LapNumber distance to that previous row
- session_max      — max K=4 PRIMARY OOF in this (Driver, Race, Year)
- session_mean     — mean K=4 PRIMARY OOF in this session
- session_count_above_prevalence — # rows in session with K=4 OOF > 0.20
- session_size     — # rows in this session
- session_rank_in_session — rank of K=4 OOF for this row among session rows
- pos_position_in_session — index of this row in session-sorted order / size
- delta_to_session_max    — K=4_row - session_max
- delta_to_lookahead      — K=4_row - lookahead (informational difference)
- perm_argmax_base — categorical: which of 4 bases predicted highest for row
- perm_argmin_base — categorical: which of 4 bases predicted lowest
- base_pred_var    — variance across the 4 base predictions
- base_pred_var_dev — base_pred_var - mean(base_pred_var) within (Compound, Stint)

Output:
    scripts/artifacts/seq_coupled_X_train.npy  (n_train, n_features)
    scripts/artifacts/seq_coupled_X_test.npy   (n_test,  n_features)
    scripts/artifacts/seq_coupled_feature_names.json
"""
from __future__ import annotations
import json
from pathlib import Path
import numpy as np
import pandas as pd
from scipy.stats import rankdata

ART = Path('scripts/artifacts')


def pos(p):
    a = np.load(p)
    return a[:, 1] if a.ndim == 2 else a


def load_bases(suffix: str):
    """Load K=4 base predictions; suffix in {'oof', 'test'}."""
    if suffix == 'oof':
        return {
            'h1d':  pos(ART / 'oof_d17_h1d_yekenot_full_strat.npy'),
            'p1cb': pos(ART / 'oof_p1_single_cb_v4_gpu_strat.npy'),
            'hgbc': pos(ART / 'oof_f1_hgbc_deep_strat.npy'),
            'd16o': pos(ART / 'oof_d16_orig_continuous_only_strat.npy'),
        }
    return {
        'h1d':  pos(ART / 'test_d17_h1d_yekenot_full_strat.npy'),
        'p1cb': pos(ART / 'test_p1_single_cb_v4_gpu_strat.npy'),
        'hgbc': pos(ART / 'test_f1_hgbc_deep_strat.npy'),
        'd16o': pos(ART / 'test_d16_orig_continuous_only_strat.npy'),
    }


def build_session_features(df_meta: pd.DataFrame, primary_pred: np.ndarray,
                           bases: dict[str, np.ndarray]) -> tuple[np.ndarray, list[str]]:
    """Compute the sequence-coupled feature block for one frame (train or test).

    df_meta has columns: Driver, Race, Year, LapNumber, Compound, Stint.
    primary_pred is the K=4 PRIMARY (rank-normalised, 1-D, 0..1).
    bases is a dict of 4 raw base predictions (1-D each).
    """
    n = len(df_meta)
    key = (df_meta['Driver'].astype(str) + '|'
           + df_meta['Race'].astype(str) + '|'
           + df_meta['Year'].astype(str)).values
    lap = df_meta['LapNumber'].astype(float).values
    order = np.lexsort((lap, key))           # stable; primary=key, secondary=lap
    key_s = key[order]
    lap_s = lap[order]
    pri_s = primary_pred[order]

    # next / prev within-session masks
    next_same = np.r_[(key_s[:-1] == key_s[1:]), False]   # row i has next-row in session
    prev_same = np.r_[False, (key_s[:-1] == key_s[1:])]   # row i has prev-row

    # ---- look-ahead / look-behind predictions and gaps ----
    look_ahead_pred_s = np.full(n, 0.20, dtype=np.float32)   # default = prevalence
    look_ahead_gap_s  = np.full(n, 99.0, dtype=np.float32)
    look_behind_pred_s = np.full(n, 0.20, dtype=np.float32)
    look_behind_gap_s  = np.full(n, 99.0, dtype=np.float32)

    look_ahead_pred_s[:-1] = np.where(next_same[:-1], pri_s[1:], 0.20)
    look_ahead_gap_s[:-1]  = np.where(next_same[:-1], lap_s[1:] - lap_s[:-1], 99.0)
    look_behind_pred_s[1:] = np.where(prev_same[1:], pri_s[:-1], 0.20)
    look_behind_gap_s[1:]  = np.where(prev_same[1:], lap_s[1:] - lap_s[:-1], 99.0)

    # ---- session-aggregate features ----
    df = pd.DataFrame({'key': key, 'lap': lap, 'pri': primary_pred})
    g = df.groupby('key')
    session_max  = g['pri'].transform('max').to_numpy(dtype=np.float32)
    session_mean = g['pri'].transform('mean').to_numpy(dtype=np.float32)
    session_size = g['pri'].transform('size').to_numpy(dtype=np.float32)
    session_count_above = g['pri'].transform(
        lambda x: (x > 0.20).sum()).to_numpy(dtype=np.float32)

    # rank of pri within session (descending — 0 = highest in session)
    session_rank = g['pri'].rank(method='min', ascending=False).to_numpy(dtype=np.float32)
    # position-in-session: index when sorted by lap / session size (0..1)
    df['lap_pos'] = g['lap'].rank(method='dense', ascending=True)
    pos_in_session = (df['lap_pos'] / session_size).to_numpy(dtype=np.float32)

    # unsort the look_ahead / look_behind back to original order
    inv = np.argsort(order)
    look_ahead_pred  = look_ahead_pred_s[inv]
    look_ahead_gap   = look_ahead_gap_s[inv]
    look_behind_pred = look_behind_pred_s[inv]
    look_behind_gap  = look_behind_gap_s[inv]

    delta_to_session_max = (primary_pred - session_max).astype(np.float32)
    delta_to_lookahead   = (primary_pred - look_ahead_pred).astype(np.float32)
    delta_to_lookbehind  = (primary_pred - look_behind_pred).astype(np.float32)

    # ---- permutation / disagreement features over the 4 bases ----
    base_arr = np.column_stack([bases[k] for k in ('h1d', 'p1cb', 'hgbc', 'd16o')])  # (n, 4)
    perm_argmax = base_arr.argmax(axis=1).astype(np.int8)
    perm_argmin = base_arr.argmin(axis=1).astype(np.int8)
    # one-hot the categorical perm_argmax / argmin (4 + 4 = 8 features)
    onehot_max = np.eye(4, dtype=np.float32)[perm_argmax]
    onehot_min = np.eye(4, dtype=np.float32)[perm_argmin]

    # base-prediction variance per row (proxy for model disagreement)
    base_var = base_arr.var(axis=1).astype(np.float32)

    # base_var deviation from mean within (Compound, Stint)
    cs_key = (df_meta['Compound'].astype(str) + '|'
              + df_meta['Stint'].astype(str)).values
    df_var = pd.DataFrame({'cs': cs_key, 'v': base_var})
    base_var_dev = (base_var - df_var.groupby('cs')['v']
                    .transform('mean').to_numpy(dtype=np.float32)).astype(np.float32)

    # spread between max and min base on the row
    base_spread = (base_arr.max(axis=1) - base_arr.min(axis=1)).astype(np.float32)

    feat_blocks = [
        ('look_ahead_pred',      look_ahead_pred[:, None]),
        ('look_ahead_gap',       look_ahead_gap[:, None]),
        ('look_behind_pred',     look_behind_pred[:, None]),
        ('look_behind_gap',      look_behind_gap[:, None]),
        ('session_max',          session_max[:, None]),
        ('session_mean',         session_mean[:, None]),
        ('session_size',         session_size[:, None]),
        ('session_count_above',  session_count_above[:, None]),
        ('session_rank',         session_rank[:, None]),
        ('pos_in_session',       pos_in_session[:, None]),
        ('delta_to_session_max', delta_to_session_max[:, None]),
        ('delta_to_lookahead',   delta_to_lookahead[:, None]),
        ('delta_to_lookbehind',  delta_to_lookbehind[:, None]),
        ('base_var',             base_var[:, None]),
        ('base_var_dev',         base_var_dev[:, None]),
        ('base_spread',          base_spread[:, None]),
        ('perm_argmax_h1d',      onehot_max[:, 0:1]),
        ('perm_argmax_p1cb',     onehot_max[:, 1:2]),
        ('perm_argmax_hgbc',     onehot_max[:, 2:3]),
        ('perm_argmax_d16o',     onehot_max[:, 3:4]),
        ('perm_argmin_h1d',      onehot_min[:, 0:1]),
        ('perm_argmin_p1cb',     onehot_min[:, 1:2]),
        ('perm_argmin_hgbc',     onehot_min[:, 2:3]),
        ('perm_argmin_d16o',     onehot_min[:, 3:4]),
    ]
    names = [n for n, _ in feat_blocks]
    X = np.concatenate([b for _, b in feat_blocks], axis=1).astype(np.float32)
    return X, names


def main():
    print('--- loading metadata + base predictions ---')
    tr = pd.read_csv('data/train.csv')
    te = pd.read_csv('data/test.csv')
    oofs = load_bases('oof')
    tests = load_bases('test')
    k4_oof = pos(ART / 'oof_K4_fwd_pathb.npy')
    k4_test = pos(ART / 'test_K4_fwd_pathb.npy')

    print(f'train rows: {len(tr):,}; test rows: {len(te):,}')
    print(f'K=4 PRIMARY OOF mean: {k4_oof.mean():.5f}; test mean: {k4_test.mean():.5f}')

    print('--- building train sequence-coupled features ---')
    X_tr, names = build_session_features(
        tr[['Driver', 'Race', 'Year', 'LapNumber', 'Compound', 'Stint']],
        k4_oof, oofs)
    print(f'X_train: shape={X_tr.shape}')

    print('--- building test sequence-coupled features ---')
    X_te, _ = build_session_features(
        te[['Driver', 'Race', 'Year', 'LapNumber', 'Compound', 'Stint']],
        k4_test, tests)
    print(f'X_test:  shape={X_te.shape}')

    np.save(ART / 'seq_coupled_X_train.npy', X_tr)
    np.save(ART / 'seq_coupled_X_test.npy',  X_te)
    (ART / 'seq_coupled_feature_names.json').write_text(json.dumps(names, indent=2))

    print(f'\n--- feature stats (train) ---')
    for i, name in enumerate(names):
        v = X_tr[:, i]
        print(f'  {name:<25} mean={v.mean():>9.4f}  std={v.std():>9.4f}  '
              f'min={v.min():>8.3f}  max={v.max():>8.3f}')


if __name__ == '__main__':
    main()
