"""scripts/dispatch_branches.py — parallel-branch brief generator.

Replaces the heavyweight BFTS proposal (AI-Scientist v2 pattern) with a
minimal coordinator: read ISSUES.md, pick N unclaimed `open` leaves,
emit a markdown brief that the PI can ratify and the agent can use to
invoke N parallel subagents.

Day-15's 4-branch parallel probe was successful but hand-orchestrated.
This script removes the typing without removing the PI's "which N
candidates?" decision (which Day-15 showed is load-bearing).

Usage:
    python scripts/dispatch_branches.py                # show open leaves
    python scripts/dispatch_branches.py --pick A B C   # build brief for A/B/C
    python scripts/dispatch_branches.py --pick A B --out audit/dispatch-DATE.md

The brief:
- echoes each picked leaf's text from ISSUES.md
- enumerates the 6-Q pre-flight per branch (PI to fill)
- provides a consolidation-table template for the audit note that
  collects results when subagents finish

The agent then invokes one parallel subagent per branch per Rule-19,
each with the standard contract (`probe.py bote → run → probe.py gate
→ audit note`). On return, agent fills the consolidation table.

Origin: `audit/2026-05-06-agentic-kaggle-research.md` item 5' (BFTS
replaced with simpler dispatch). MAST FC2 inter-agent-misalignment
finding (32.4% of multi-agent failures) keeps PI as the picker.
"""
from __future__ import annotations

import argparse
import re
import sys
from datetime import date
from pathlib import Path

ISSUES = Path("ISSUES.md")
AUDIT = Path("audit")


def parse_open_leaves(path: Path = ISSUES) -> list[dict]:
    """Return list of {leaf_id, title, body, owner, status} for each
    [owner: ... | status: ...] block in ISSUES.md whose status is
    'open' or 'wip'.
    """
    if not path.exists():
        raise SystemExit(f"{path} not found")
    text = path.read_text()
    leaves: list[dict] = []
    pattern = re.compile(
        r"-\s+\*\*(?P<lid>[\w.]+)\.\*\*\s+(?P<rest>.+?)"
        r"\[owner:\s*(?P<owner>[^|]+?)\s*\|\s*status:\s*(?P<status>\w+)\]",
        re.DOTALL,
    )
    for m in pattern.finditer(text):
        rest = m.group("rest").strip()
        first_line = rest.splitlines()[0].rstrip(".")[:120] if rest else ""
        leaves.append(dict(
            leaf_id=m.group("lid"),
            title=first_line,
            body=rest[:600],
            owner=m.group("owner").strip(),
            status=m.group("status").strip(),
        ))
    return leaves


def show_open_leaves(leaves: list[dict]) -> None:
    open_leaves = [l for l in leaves if l["status"] in {"open", "wip"}]
    if not open_leaves:
        print("(no open or wip leaves found in ISSUES.md)")
        return
    print(f"# Open / wip ISSUES.md leaves ({len(open_leaves)} total)")
    print()
    for l in open_leaves:
        flag = "wip" if l["status"] == "wip" else "open"
        owner = l["owner"] if l["owner"] != "unclaimed" else "—"
        print(f"  {l['leaf_id']:6s}  [{flag:4s}]  owner={owner}")
        print(f"          {l['title']}")
        print()
    print("Pick N with: python scripts/dispatch_branches.py --pick "
          + " ".join(l["leaf_id"] for l in open_leaves[:3]))


BRIEF_TEMPLATE = """# Parallel-branch dispatch — {today}

> Generated by `scripts/dispatch_branches.py`. {n} candidates picked
> from ISSUES.md. PI ratifies the picks; agent runs {n} parallel
> subagents (one per leaf), each following the standard probe.py
> bote → run → probe.py gate → audit-note contract.

## Picks

{picks_block}

## 6-Q pre-flight (PI fills — Rule 16)

For each pick above, PI commits answers to chat BEFORE the dispatch
fires. Agent must NOT proceed without these. Format per pick:

```
LEAF_ID:
  Q1 family in mechanism_families_explored?
  Q2 rank-lock-vulnerable bucket?
  Q3 predicted standalone OOF (cite precedent):
  Q4 predicted ρ vs PRIMARY:
  Q5 closest gate-PASS/FAIL precedent:
  Q6 training objective matches row-AUC?  (Rule 16; --metric-aligned)
  PI-predicted LB Δ (bp):
```

## Consolidation table (agent fills on return)

| leaf | std OOF | ρ vs PRIMARY | min-meta Δ bp | gate verdict | audit note |
|---|---:|---:|---:|---|---|
{rows_block}

## End-of-dispatch checklist (Rule 18 / 19)

- [ ] Each leaf's status updated in ISSUES.md (`wip` → `done` / `null` /
      `parked`).
- [ ] Each leaf has a per-probe audit note `audit/YYYY-MM-DD-<leaf>.md`.
- [ ] Friction-tag append for any unexpected outcome
      (`audit/friction.md`).
- [ ] One consolidated dispatch-result note
      `audit/dispatch-{today}.md` referencing all per-probe notes.
- [ ] Any candidate worth submitting → BOTE (Rule 19a) with PI sealed
      prediction (Rule 20a) FIRST.
"""


def build_brief(leaves: list[dict], picks: list[str]) -> str:
    leaf_by_id = {l["leaf_id"]: l for l in leaves}
    missing = [p for p in picks if p not in leaf_by_id]
    if missing:
        raise SystemExit(f"unknown leaf id(s): {missing}; "
                         f"open leaves: {[l['leaf_id'] for l in leaves]}")

    picks_block_parts: list[str] = []
    rows: list[str] = []
    for lid in picks:
        l = leaf_by_id[lid]
        picks_block_parts.append(
            f"### {lid}  (owner={l['owner']} | status={l['status']})\n\n"
            f"{l['body']}\n"
        )
        rows.append(f"| `{lid}` |   |   |   |   |   |")

    return BRIEF_TEMPLATE.format(
        today=date.today().isoformat(),
        n=len(picks),
        picks_block="\n".join(picks_block_parts),
        rows_block="\n".join(rows),
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pick", nargs="+", default=None,
                    help="leaf IDs to dispatch (e.g. 1c 2a 3c)")
    ap.add_argument("--out", default=None,
                    help="write brief to this path (default audit/dispatch-DATE.md)")
    args = ap.parse_args()

    leaves = parse_open_leaves()

    if not args.pick:
        show_open_leaves(leaves)
        return

    if not 1 <= len(args.pick) <= 5:
        raise SystemExit("pick 1-5 leaves (Rule 19e: many small things; "
                         "Day-15 4-branch was the load-bearing precedent)")

    brief = build_brief(leaves, args.pick)
    today = date.today().isoformat()
    out = Path(args.out) if args.out else AUDIT / f"dispatch-{today}.md"
    if out.exists() and not args.out:
        print(f"⚠ {out} already exists. Pass --out to override.",
              file=sys.stderr)
        sys.exit(1)
    AUDIT.mkdir(parents=True, exist_ok=True)
    out.write_text(brief)
    print(f"→ {out}")
    print(f"\nNext: PI fills 6-Q answers in chat for "
          f"{', '.join(args.pick)}; agent then dispatches parallel subagents.")


if __name__ == "__main__":
    main()
