"""scripts/probe_r12_cb_resid.py — Round 12 Phase 1: CatBoost on R7.1 residual.

Train a CatBoost REGRESSOR on the residual target `r = y − OOF_R7.1`,
using cb_v4's full FE pipeline (yekenot recipe + FS_A + per-fold CV TE).
The predicted residual is by-construction ρ-orthogonal to R7.1 PRIMARY:
the residual IS the orthogonal complement of R7.1 to y. This is the
plan-agent's identified high-EV orthogonality lever for breaking the
K=13+Path-B rank-lock.

Per the plan-agent BOTE: P(G2-clear) ≈ 0.30, E[Δ vs R7.1] ≈ +0.15 bp.

Fold-safety:
- `make_features_static` + per-fold `fit_fs_a` / `apply_fs_a` (Rule 24).
- Per-fold CV TE via `cv_target_encode` (re-fits stats on training rows only).
- Residual target `r = y − oof_R71` uses oof_R71 generated by R7.1's own
  StratifiedKFold(seed=42) — each row's oof_R71 was produced by a model
  that did not see its own label. R12 uses the SAME 5-fold splits, so
  each row is in val of exactly one fold for both R7.1 and R12. Standard
  stacking convention; not strictly nested-CV but the standard practice
  for stacking residuals (same convention K=13 itself uses).

Gates:
- G1 standalone AUC ≥ 0.945 (cb_v4 territory). The residual prediction
  must rank-order rows usefully.
- G2 K=14 + Path-B DCS τ=100k Δ vs R7.1 PRIMARY ≥ +0.10 bp.
- G3 ρ_OOF vs cb_v4 ≤ 0.998 (orthogonality verification).

Output: rank-normalized residual prediction in (0, 1) — required because
Path-B's `expand` does logit() which would break on negative residuals.

Usage:
  python scripts/probe_r12_cb_resid.py [--smoke] [--max-rounds 3000]
"""
from __future__ import annotations
import argparse
import json
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
import catboost as cb
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold
from scipy.stats import spearmanr, rankdata

sys.path.insert(0, str(Path(__file__).parent))
from p1_features import (
    TE_CONFIGS, apply_fs_a, cv_target_encode, feature_columns_for_lgbm,
    fit_fs_a, make_features_static,
)
from p1_single_cb import fold_safe_te_for_fold

ART = Path("scripts/artifacts")
TARGET, ID_COL = "PitNextLap", "id"
SEED, N_FOLDS = 42, 5

REF_OOF = ART / "oof_K13_pathb_driverclass_stint_tau100000.npy"
REF_TEST = ART / "test_K13_pathb_driverclass_stint_tau100000.npy"
CB_V4_OOF = ART / "oof_p1_single_cb_v4_gpu_strat.npy"


def cb_resid_params(max_iters: int, seed: int, depth: int = 6) -> dict:
    """CatBoost regression on residual. Smaller + slower than cb_v4
    because residual signal is fragile (calibrated-R7.1-base means
    most exploitable signal is in tail bins, not bulk distribution)."""
    return dict(
        loss_function="RMSE",
        eval_metric="RMSE",
        iterations=max_iters,
        learning_rate=0.03,
        depth=depth,
        l2_leaf_reg=12.0,
        one_hot_max_size=10,
        bootstrap_type="Bernoulli",
        subsample=0.8,
        min_data_in_leaf=40,
        od_type="Iter",
        od_wait=500,
        random_seed=seed,
        verbose=500,
        allow_writing_files=False,
        task_type="CPU",
        thread_count=-1,
        rsm=0.7,
    )


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--smoke", action="store_true")
    ap.add_argument("--max-rounds", type=int, default=4000)
    ap.add_argument("--depth", type=int, default=6)
    args = ap.parse_args()

    t0 = time.time()
    print("== R12-1: cb_resid (CatBoost regression on R7.1 OOF residual) ==",
          flush=True)

    train = pd.read_csv("data/train.csv")
    test = pd.read_csv("data/test.csv")
    print(f"  train {train.shape}  test {test.shape}", flush=True)

    oof_R71 = np.load(REF_OOF)
    test_R71 = np.load(REF_TEST)
    y_all = train[TARGET].astype(int).values
    auc_R71 = float(roc_auc_score(y_all, oof_R71))
    print(f"  R7.1 OOF AUC (verify): {auc_R71:.6f} (expect 0.954471)",
          flush=True)
    if abs(auc_R71 - 0.954471) > 1e-4:
        print(f"  WARN: R7.1 AUC mismatch -- proceeding anyway", flush=True)

    # Residual target (original train.csv order)
    residual = (y_all.astype(np.float64) - oof_R71).astype(np.float32)
    print(f"  residual: min {residual.min():.3f}  max {residual.max():.3f}  "
          f"mean {residual.mean():.4f}  std {residual.std():.4f}", flush=True)

    if args.smoke:
        idx = np.random.default_rng(SEED).choice(len(train), 50_000,
                                                  replace=False)
        train = train.iloc[idx].reset_index(drop=True)
        residual = residual[idx]
        oof_R71 = oof_R71[idx]
        y_all = train[TARGET].astype(int).values
        print(f"  SMOKE: subset to {train.shape}", flush=True)

    # Attach residual as carry-through column
    train["_resid"] = residual

    # FE pipeline (cb_v4 recipe)
    train_S, state = make_features_static(train, fit=True)
    test_S, _ = make_features_static(test, fit=False, state=state)
    y = train_S[TARGET].astype(int).reset_index(drop=True)
    resid_sorted = train_S["_resid"].astype(np.float32).reset_index(drop=True)

    # Canonical feature list via sample fold
    skf = StratifiedKFold(N_FOLDS, shuffle=True, random_state=SEED)
    fold_list = list(skf.split(np.zeros(len(y)), y))
    sample_ti = fold_list[0][0]
    sample_fs_a = fit_fs_a(train_S.iloc[sample_ti])
    sample_train = apply_fs_a(train_S, sample_fs_a)
    feats, cat_cols = feature_columns_for_lgbm(sample_train)
    for c in ("Year", "Stint"):
        if c in feats and c not in cat_cols:
            cat_cols.append(c)
    feats = feats + [n for _, _, n in TE_CONFIGS]
    feats = [f for f in feats if f != "_resid"]  # never use target as feature
    print(f"  feats: {len(feats)}  cat: {len(cat_cols)}", flush=True)

    # Map sorted-order indices back to original train.csv ID-order at save
    sorted_ids = train_S[ID_COL].values
    orig_train_ids = train[ID_COL].values
    id_to_orig_pos = {tid: i for i, tid in enumerate(orig_train_ids)}
    id_to_sorted_pos = {tid: i for i, tid in enumerate(sorted_ids)}
    test_sorted_ids = test_S[ID_COL].values
    test_orig_ids = test[ID_COL].values
    test_id_to_sorted_pos = {tid: i for i, tid in enumerate(test_sorted_ids)}

    # OOF R7.1 mapped to SORTED order, for ρ_OOF computation
    oof_R71_sorted = np.array([oof_R71[id_to_orig_pos[t]] for t in sorted_ids],
                              dtype=np.float32)

    # 5-fold loop
    oof_resid_pred = np.zeros(len(y), dtype=np.float64)
    test_pred = np.zeros(len(test_S), dtype=np.float64)
    fold_metrics = []
    n_eff_folds = 1 if args.smoke else N_FOLDS

    for fold, (ti, vi) in enumerate(fold_list[:n_eff_folds], 1):
        t_f = time.time()
        print(f"\n  --- Fold {fold}/{n_eff_folds} | ti={len(ti)} va={len(vi)} ---",
              flush=True)

        fs_a = fit_fs_a(train_S.iloc[ti])
        train_ti = apply_fs_a(train_S.iloc[ti].reset_index(drop=True), fs_a)
        train_va = apply_fs_a(train_S.iloc[vi].reset_index(drop=True), fs_a)
        test_fold = apply_fs_a(test_S, fs_a)

        y_ti = train_ti[TARGET].astype(int).reset_index(drop=True)
        fold_safe_te_for_fold(train_ti, train_va, test_fold,
                              y_ti, fold, N_FOLDS)

        X_tr = train_ti.reindex(columns=feats, fill_value=0).copy()
        X_va = train_va.reindex(columns=feats, fill_value=0).copy()
        X_te = test_fold.reindex(columns=feats, fill_value=0).copy()
        for c in cat_cols:
            X_tr[c] = X_tr[c].astype("int32")
            X_va[c] = X_va[c].astype("int32")
            X_te[c] = X_te[c].astype("int32")
        num_cols = [c for c in feats if c not in cat_cols]
        for X in (X_tr, X_va, X_te):
            X[num_cols] = X[num_cols].fillna(0).astype(np.float32)
        cat_idx = [feats.index(c) for c in cat_cols]

        # Residual targets in sorted-order
        r_ti = resid_sorted.iloc[ti].values
        r_va = resid_sorted.iloc[vi].values

        params = cb_resid_params(args.max_rounds, SEED, depth=args.depth)
        m = cb.CatBoostRegressor(**params)
        m.fit(X_tr, r_ti, eval_set=(X_va, r_va),
              cat_features=cat_idx, use_best_model=True)

        r_pred_va = m.predict(X_va)
        r_pred_te = m.predict(X_te)
        oof_resid_pred[vi] = r_pred_va
        test_pred += r_pred_te / n_eff_folds

        # Per-fold sanity AUC: rank-mapped residual as a standalone ranker
        y_va = train_va[TARGET].astype(int).values
        try:
            auc_resid = float(roc_auc_score(y_va, r_pred_va))
        except ValueError:
            auc_resid = float("nan")
        # Combined R7.1 + r_pred (logit add) — diagnostic
        oof_R71_va = oof_R71_sorted[vi]
        try:
            auc_combined = float(roc_auc_score(y_va, oof_R71_va + r_pred_va))
        except ValueError:
            auc_combined = float("nan")

        wall = time.time() - t_f
        fold_metrics.append(dict(
            fold=fold, n_ti=int(len(ti)), n_va=int(len(vi)),
            iters=int(m.tree_count_), wall_s=float(wall),
            auc_va_resid=auc_resid,
            auc_va_combined=auc_combined,
            auc_va_R71_alone=float(roc_auc_score(y_va, oof_R71_va)),
            r_pred_range=[float(r_pred_va.min()), float(r_pred_va.max())],
        ))
        print(f"    iters={m.tree_count_}  wall {wall:.0f}s", flush=True)
        print(f"    AUC R7.1 alone: {fold_metrics[-1]['auc_va_R71_alone']:.5f}",
              flush=True)
        print(f"    AUC residual alone: {auc_resid:.5f}", flush=True)
        print(f"    AUC R7.1 + residual: {auc_combined:.5f}", flush=True)

    if args.smoke:
        print(f"\n  SMOKE wall: {time.time()-t0:.0f}s; full 5-fold projection "
              f"≈ {(time.time()-t0) * N_FOLDS:.0f}s", flush=True)
        return

    # Standalone OOF metrics (rank of raw residual prediction = G1 proxy)
    auc_resid_alone = float(roc_auc_score(y.values, oof_resid_pred))
    auc_combined = float(roc_auc_score(y.values, oof_R71_sorted + oof_resid_pred))
    rho_resid_vs_R71, _ = spearmanr(oof_resid_pred, oof_R71_sorted)

    # ρ vs cb_v4
    rho_resid_vs_cbv4 = None
    if CB_V4_OOF.exists():
        cb_v4_oof = np.load(CB_V4_OOF)
        cb_v4_oof_p = cb_v4_oof[:, 1] if cb_v4_oof.ndim == 2 else cb_v4_oof
        cb_v4_sorted = np.array([cb_v4_oof_p[id_to_orig_pos[t]]
                                  for t in sorted_ids])
        rho_resid_vs_cbv4, _ = spearmanr(oof_resid_pred, cb_v4_sorted)

    print(f"\n  Standalone OOF AUC (residual alone): {auc_resid_alone:.5f}",
          flush=True)
    print(f"  Combined OOF AUC (R7.1 + residual): {auc_combined:.5f}",
          flush=True)
    print(f"  ρ_OOF residual vs R7.1: {rho_resid_vs_R71:.6f}", flush=True)
    if rho_resid_vs_cbv4 is not None:
        print(f"  ρ_OOF residual vs cb_v4: {rho_resid_vs_cbv4:.6f}", flush=True)

    # Rank-normalize residual prediction to (eps, 1-eps) for Path-B add.
    # Combined-frame rank-norm so train and test share the same distribution
    # (path-B's per-segment LR + expand() needs a usable logit; raw residual
    # can be negative which would break logit).
    combined = np.concatenate([oof_resid_pred, test_pred])
    combined_ranks = rankdata(combined)
    eps = 1.0 / (2 * len(combined_ranks))
    combined_uniform = (combined_ranks - 0.5) / len(combined_ranks)
    combined_uniform = np.clip(combined_uniform, eps, 1 - eps)
    oof_base_sorted = combined_uniform[:len(oof_resid_pred)]
    test_base_sorted = combined_uniform[len(oof_resid_pred):]

    # Map back to original CSV order before saving
    order_back_train = np.array([id_to_sorted_pos[t] for t in orig_train_ids])
    order_back_test = np.array([test_id_to_sorted_pos[t]
                                 for t in test_orig_ids])
    oof_base_orig = oof_base_sorted[order_back_train]
    test_base_orig = test_base_sorted[order_back_test]

    np.save(ART / "oof_R12_cb_resid_strat.npy",
            oof_base_orig.astype(np.float32))
    np.save(ART / "test_R12_cb_resid_strat.npy",
            test_base_orig.astype(np.float32))
    # Also save the raw residual predictions (in original CSV order) for diagnostics
    oof_resid_raw = oof_resid_pred[order_back_train].astype(np.float32)
    test_resid_raw = test_pred[order_back_test].astype(np.float32)
    np.save(ART / "oof_R12_cb_resid_raw.npy", oof_resid_raw)
    np.save(ART / "test_R12_cb_resid_raw.npy", test_resid_raw)
    print(f"  Saved oof_R12_cb_resid_strat.npy + test_..._strat.npy "
          f"(rank-normalized to (eps, 1-eps))", flush=True)
    print(f"  Saved oof_R12_cb_resid_raw.npy + test_..._raw.npy "
          f"(raw residual predictions, diagnostics)", flush=True)

    summary = dict(
        round="R12_Phase1_cb_resid",
        oof_auc_resid=auc_resid_alone,
        oof_auc_combined=auc_combined,
        oof_auc_R71_ref=auc_R71,
        rho_resid_vs_R71=float(rho_resid_vs_R71),
        rho_resid_vs_cbv4=(float(rho_resid_vs_cbv4)
                            if rho_resid_vs_cbv4 is not None else None),
        fold_metrics=fold_metrics,
        wall_total_s=time.time() - t0,
        depth=args.depth,
        max_rounds=args.max_rounds,
    )
    out_json = Path("audit/2026-05-19-round-12-cb_resid.json")
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps(summary, indent=2))
    print(f"  Wrote {out_json}", flush=True)
    print(f"  Total wall: {time.time()-t0:.0f}s", flush=True)


if __name__ == "__main__":
    main()
